### ISSUE TITLE
Axios interceptor

### ISSUE THREAD

**Issue by task11** [task11/github-gg-react-typescript-frontend#22]
## Todo
- [x] git secret token 환경변수 설정
- [x] axios interceptor 설정
- [x] api calling check
