### ISSUE TITLE
Search detail page

### ISSUE THREAD

**Issue by task11** [task11/github-gg-react-typescript-frontend#29]
## Todo
- [x] Search detail page layout
- [x] Search detail content
- [x] Content item card
- [x] Navigate to user detail page
