### ISSUE TITLE
User detail page

### ISSUE THREAD

**Issue by task11** [task11/github-gg-react-typescript-frontend#31]
## Todo
- [ ] User page layout
- [ ] fetching user info
- [ ] fetching user repository (infinite scroll)
