### ISSUE TITLE
Feature view latest users 3 commits

### ISSUE THREAD

**Issue by task11** [task11/github-gg-react-typescript-frontend#70]
## Description
유저의 최근 커밋을 보여주는 기능

## Todo
- [x] Add API components
- [x] Definition Request Type
- [x] Add layout & components
