### ISSUE TITLE
Migrate State Management from Recoil to Jotai

### ISSUE THREAD

**Issue by task11** [task11/github-gg-react-typescript-frontend#83]
## Description
상태 관리 라이브러리를 Recoil에서 Jotai로 전환

## Objectives
- 기존 기능을 잃지 않으면서 Recoil에서 Jotai로 전환
- 상태 관리에 영향을 받는 모든 컴포넌트와 hooks, 테스트 코드 업데이트
- 상태 관리의 성능과 유지 보수성 향상
- Jotai 라이브러리 도입을 통한 학습

## Tasks
- [x] Recoil의 현재 구현 방식 확인
- [x] Recoil에 의존하는 모든 컴포넌트, 훅 등을 확인
- [x] feature 브랜치에서 Recoil to Jotai로 마이그레이션 구현
- [x] 코드 테스트 수행
- [x] 상태 관리 라이브러리 변경을 반영하여 프로젝트 문서 업데이트
- [x] feature -> dev -> release -> main 순서로 병합

## Expected Outcome
- 다양한 상태관리 라이브러리의 개념 학습
- 서비스 동작은 동일하되 사용자에게 눈에 띄는 차이가 없어야 함
